name: Add Template

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the Template'
        required: true
        type: string
      body:
        description: |
          Markdown body of the Template.
          You can paste your Markdown content directly here.
        required: true
        type: string

jobs:
  add_template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install jq

    - name: Add new template to templates.json
      run: |
        # Fetch input values
        TITLE="${{ github.event.inputs.title }}"
        BODY="${{ github.event.inputs.body }}"

        # Escape special characters (including quotes and newlines) in the body
        ESCAPED_BODY=$(echo "$BODY" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')

        # Escape the TITLE properly
        ESCAPED_TITLE=$(echo "$TITLE" | sed 's/"/\\"/g')

        # Check if templates.json exists
        if [ ! -f templates.json ]; then
          echo "[]"> templates.json  # Create an empty array if the file does not exist
        fi

        # Add the new template to templates.json, ensuring correct escaping
        jq --arg title "$ESCAPED_TITLE" --arg body "$ESCAPED_BODY" \
          '. += [{"title": $title, "body": $body}]' templates.json > temp.json && mv temp.json templates.json

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add templates.json
        git commit -m "Add new template: ${{ github.event.inputs.title }}"

        # Use the GITHUB_TOKEN for authentication when pushing
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/L0Lock/BCom-Toolbox.git
    
