name: Update Templates JSON

on:
  workflow_dispatch:

jobs:
  update_templates_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Convert templates.md to templates.json
      run: |
        python3 convert_templates.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add templates.json
        git commit -m "Update templates.json from templates.md"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/L0Lock/BCom-Toolbox.git
